#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 320
#define WINDOW_HEIGHT 240

#define IMAGE_LABEL_WIDTH 240
#define IMAGE_LABEL_HEIGHT 180

#define IMAGE_LABEL_WIDTH_2 160
#define IMAGE_LABEL_HEIGHT_2 120

#define IMAGE_LABEL_WIDTH_3 200
#define IMAGE_LABEL_HEIGHT_3 150

#define IMAGE_LABEL_WIDTH_4 100
#define IMAGE_LABEL_HEIGHT_4 75

#define USE_NEURO

#endif // CONSTANTS_H
